### ISSUE TITLE
Error on Common Setup Phase

### ISSUE THREAD

**Issue by Lordbaane** [team-abnormals/buzzier-bees#48]
This is and intermittent error that occurs with several mods, Autumnity, Berry Good and Quark as well.
https://pastebin.com/H3zJwT6H

**Comment by pau101** [comment]
_linking for records sake_ Markus1002/Autumnity/issues/11

In regards to this crash:

Buzzier Bees is registering compostability during the parallel dispatched common setup event. Since this event is fired in parallel, multiple mods performing registration during it create a race condition of whether this reported issue will occur. Mods should register compostability as well as other non synchronized data (nearly everything done in [setup](https://github.com/bageldotjpg/Buzzier-Bees/blob/387ca32bdf8caa3378cf31f47f253f3edb39419a/src/main/java/com/bagel/buzzierbees/core/BuzzierBees.java#L85-L99)) during relevant registry events or `DeferredWorkQueue` if necessary.

**Comment by Vaelzan** [comment]
Should be fixed in this pull request: https://github.com/bageldotjpg/Buzzier-Bees/pull/62

**Comment by bageldotjpg** [comment]
Yep, fixed in the latest update
