### ISSUE TITLE
Night Vision Flicker

### ISSUE THREAD

**Issue by ChloeDawn** [team-abnormals/buzzier-bees#70]
Due to the short length of the effects you apply for scented candles, night vision produces a permanent "expiring" flicker. I would suggest applying the effects with a longer length and sooner renewal, similar to beacon effects.

**Mod version:** 1.5.2

**Comment by bageldotjpg** [comment]
Yeah I'm aware of this, it's an unfortunate side effect of how night vision works. I don't want to make Scented Candles have longer length because it'd need to be like, 25 seconds for it to not flicker with Night Vision and I want it to be as instant as possible when leaving the radius of the candle to lose the effect to keep them as balanced as possible. I may look into other forms such as a night vision effect that doesn't flicker when ending, but basically yeah this is how it's going to be
